/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplouniversidad.vistas;

/**
 *
 * @author karina
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMformulario = new javax.swing.JMenu();
        jFormularioAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jFormulariodmateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmanejodeins = new javax.swing.JMenuItem();
        jCargadenotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jlistadopormateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jMformulario.setText("Alumno");
        jMformulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformularioActionPerformed(evt);
            }
        });

        jFormularioAlumno.setText("Formulario de Alumno");
        jFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormularioAlumnoActionPerformed(evt);
            }
        });
        jMformulario.add(jFormularioAlumno);

        jMenuBar1.add(jMformulario);

        jMenu2.setText("materia");

        jFormulariodmateria.setText("Formulario de Materia");
        jFormulariodmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormulariodmateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jFormulariodmateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        jmanejodeins.setText("Manejo de Inscripciones");
        jmanejodeins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanejodeinsActionPerformed(evt);
            }
        });
        jMenu3.add(jmanejodeins);

        jCargadenotas.setText("Manipulacion de notas");
        jCargadenotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargadenotasActionPerformed(evt);
            }
        });
        jMenu3.add(jCargadenotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consulta");

        jlistadopormateria.setText("Alumnos por materia");
        jlistadopormateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistadopormateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jlistadopormateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormularioAlumnoActionPerformed
        escritorio.removeAll();
       escritorio.repaint();
        FormularioDeAlumno fda=  new FormularioDeAlumno();
        fda.setVisible(true);
        escritorio.add(fda);
        escritorio.moveToFront(fda); // TODO add your handling code here:
    }//GEN-LAST:event_jFormularioAlumnoActionPerformed

    private void jMformularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformularioActionPerformed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMformularioActionPerformed

    private void jFormulariodmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormulariodmateriaActionPerformed
      GestionDeMateria gdm=new GestionDeMateria();
      gdm.setVisible(true);
      escritorio.add(gdm);
      escritorio.moveToFront(gdm);
    }//GEN-LAST:event_jFormulariodmateriaActionPerformed

    private void jmanejodeinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanejodeinsActionPerformed
     Inscripcion ins=new Inscripcion();
     ins.setVisible(true);
     escritorio.add(ins);
     escritorio.moveToFront(ins);
    }//GEN-LAST:event_jmanejodeinsActionPerformed

    private void jCargadenotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargadenotasActionPerformed
     CargaDeNotas cdn=new CargaDeNotas();
     cdn.setVisible(true);
     escritorio.add(cdn);
     escritorio.moveToFront(cdn);
    }//GEN-LAST:event_jCargadenotasActionPerformed

    private void jlistadopormateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistadopormateriaActionPerformed
       ListadoDeAlumnoPorMateria ldapm=new ListadoDeAlumnoPorMateria();
       ldapm.setVisible(true);
escritorio.add(ldapm);
escritorio.moveToFront(ldapm);// TODO add your handling code here:
    }//GEN-LAST:event_jlistadopormateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jCargadenotas;
    private javax.swing.JMenuItem jFormularioAlumno;
    private javax.swing.JMenuItem jFormulariodmateria;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMformulario;
    private javax.swing.JMenuItem jlistadopormateria;
    private javax.swing.JMenuItem jmanejodeins;
    // End of variables declaration//GEN-END:variables
}
